<script>
    import Card from "$lib/components/container/Card.svelte";
    import Line from "$lib/components/elements/geometry/Line.svelte";
    import Link from "$lib/components/elements/texts/Link.svelte";
    import Text from "$lib/components/elements/texts/Text.svelte";
    import Title from "$lib/components/elements/Title.svelte";
    import PageBottom from "$lib/components/space/PageBottom.svelte";
</script>

<Title text="Privacy Policy"/>

<span class="text-center">
    <Text header size="xl-auto">Privacy Policy</Text>
</span>

<div class="w-10/12 sm:w-11/12 mx-auto mt"><Card>
    <div class="flex flex-col gap-4">
        <Text size="small">Update : March 16 2022</Text>

        <Text>This privacy policy is intended to tell you how we collect your personal information when you create an account on our site. If you have any questions about your personal information, please contact us via our e-mail contact@tchoo.pet. By using the services, you consent to this policy and to the processing of your data in the manner set out in this policy. If you do not agree with these terms, please do not use the services.</Text>
        
        <Line/>

        <Text size="large">Definitions</Text>
        <ul class="list-disc ml-8">
            <Text><li><span class="font-bold">The Tchoos</span> represents the self-employed <span class="font-bold">Camille Dugas</span>:</li></Text>
            <ul class="list-disc ml-8">
                <Text><li>Location: France, Europe</li></Text>
                <Text><li>E-Mail : contact@tchoo.pet</li></Text>
                <Text><li>SIRET n°881 460 679 00015</li></Text>
                <Text><li>VAT not applicable, art. 293 B of the CGI.</li></Text>
            </ul>
            <Text><li><span class="font-bold">website</span> represents our website at <Link href="https://tchoo.pet" target="external">https://tchoo.pet</Link></li></Text>
            <Text><li><span class="font-bold">application</span> represents our mobile application to download on the following links:</li></Text>
            <ul class="list-disc ml-8">
                <!-- TODO : set the good links -->
                <Text><li><Link href="https://play.google.com/store/apps/details?id=com.tchoo.pet" target="external">Play Store (Google)</Link></li></Text>
                <Text><li><Link href="https://apps.apple.com/us/app/tchoo-pet/id1498797554" target="external">App Store (Apple)</Link></li></Text>
            </ul>
        </ul>

        <Line/>

        <Text size="large">Who is responsible for my personal data ?</Text>
        <Text>The person responsible for the personal data collected on our website is The Tchoos.</Text>

        <Line/>

        <Text>By using the services offered by The Tchoos, you declare to have understood and accepted without reservation the terms of this chart.</Text>

        <Text size="large">Information we collect</Text>
        <Text>The Tchoos certain data, we strive to ensure that the data we collect about you is stored securely.</Text>
        <Text>The information we collect about you includes:</Text>
        <ul class="list-disc ml-8">
            <Text><li>your username</li></Text>
            <Text><li>your password (hashed)</li></Text>
            <Text><li>your login token (UUID randomly generated by the server when you connect)</li></Text>
            <Text><li>information on your Elrond wallet linked to the site : provider (web wallet, maiar app, extension, ledger), public address (the one used to receive EGLD), signature (generated from the public address and your token)</li></Text>
            <Text><li>information about the NFT and his statistics related to the application application</li></Text>
        </ul>

        <Text size="large">Who has access to your personal data and is it shared ?</Text>
        <Text>We never sell personally identifiable information to other companies, and we do not share your information with anyone outside our network. All information we store is for network development or strictly internal use.</Text>
        <Text>Some data may be seen by visitors/users of our website or of our application, the data concerned are specified in this chart.</Text>

        <Text size="large">Use of personal data</Text>
        <Text>The Tchoos uses the information we collect in the following ways:</Text>
        <ul class="list-disc ml-8">
            <Text><li>allow automatic login and manage your account.</li></Text>
            <Text><li>allow you to make transactions on the site from your Elrond wallet</li></Text>
            <Text><li>manage your NFT statistics on our application and on our website (these statistics can be seen by any user)</li></Text>
        </ul>

        <Line/>

        <Text size="large">Modification of the policy</Text>
        <Text>The Tchoos reserves the right to change this policy at any time. If the information in this policy changes in the future, you will be asked to read it again.</Text>

        <Text size="large">Acceptation of the policy</Text>
        <Text>By browsing our website or our application, you agree to this policy. Please do not use our services if you do not agree to our privacy policy.</Text>
    </div>
</Card></div>

<PageBottom/>