name: Update on the server after a commit on the main branch

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.14'

      - name: Install npm dependencies
        run: npm install
        
      - name: Run build task
        run: npm run build
        
      - name: Copy files via scp
        uses: appleboy/scp-action@master              
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./build"
          target: "/home/Tchoos-website/"
